# HOW-TO:
#
# docker compose  create
# docker compose run -d fileindexer
# docker compose stop fileindexer
#
services:
  fileindexerapp:
    build: ./fileindexer-app
    container_name: fileindexerapp
    hostname: fileindexerapp
    depends_on:
      - fileindexerindex
    links:
      - fileindexerindex
    ports:
      - "8080:8080"
    networks:
      - fileindexer-network

  fileindexerreverseproxy:
    build: ./fileindexer-reverse-proxy
    container_name: fileindexerreverseproxy
    hostname: fileindexerreverseproxy
    ports:
      - "8081:80"
    networks:
      - fileindexer-network
  
  fileindexerindex:
    build: ./fileindexer-index
    container_name: fileindexerindex
    ports:
      - "9042:9042"
    expose:
      - "9042"
    networks:
      - fileindexer-network
    volumes:
      - fileindexerindex_node_data:/temp/fileindexerindex/container-volume/

volumes:
  fileindexerindex_node_data:

networks:
  fileindexer-network: {}