# HOW-TO:
#
# docker compose  create
# docker compose run -d fileindexer
# docker compose stop fileindexer
#
services:
  fileindexerapp:
    build: ./fileindexer-app
    container_name: fileindexerapp
    hostname: fileindexerapp
    depends_on:
      - fileindexerindex
    links:
      - fileindexerindex
    ports:
      - "8080:8080"
    networks:
      - fileindexer-network

  fileindexerreverseproxy:
    build: ./fileindexer-reverse-proxy
    container_name: fileindexerreverseproxy
    hostname: fileindexerreverseproxy
    ports:
      - "8081:80"
    networks:
      - fileindexer-network
  
  fileindexerindex:
    image: cassandra:4.1.1
    logging:
      options:
        max-size: "5m"
        max-file: "1"
    container_name: fileindexerindex
    hostname: fileindexerindex
    ports:
      - "127.0.0.1:9042:9042"
    expose:
      - "9042"
    networks:
      - fileindexer-network
    volumes:
      - fileindexerindex_node_data:/temp/fileindexerindex/container-volume/

volumes:
  fileindexerindex_node_data:

networks:
  fileindexer-network: {}