# HOW-TO:
#
# docker compose  create
# docker compose run -d fileindexer
# docker compose stop fileindexer
#
services:
  fileindexerapp:
    build: ./fileindexer-app
    depends_on:
      - fileindexerindex
    links:
      - fileindexerindex
    ports:
      - "8080:8080"
    networks:
      - fileindexer-network

  fileindexerreverseproxy:
    build: ./fileindexer-reverse-proxy
    networks:
      - fileindexer-network
    ports:
      - "8081:80"

  fileindexerindex:
    image: cassandra:4.1.1
    networks:
      - fileindexer-network
    ports:
      - "9042:9042"

networks:
  fileindexer-network: {}